services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: rimboking_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - rimboking
    depends_on:
      - mysql
      - redis
    user: root
    command:
      - sh
      - -c
      - "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && chmod -R 775 /var/www/storage /var/www/bootstrap/cache && php-fpm"

  nginx:
    image: nginx:stable-alpine
    container_name: rimboking_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rimboking
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: rimboking_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rimboking_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rimboking
      MYSQL_PASSWORD: rimboking
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rimboking

  redis:
    image: redis:alpine
    container_name: rimboking_redis
    restart: unless-stopped
    networks:
      - rimboking

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: rimboking_queue
    restart: unless-stopped
    working_dir: /var/www
    user: root
    command: php artisan queue:work redis --sleep=3 --tries=3 --timeout=90
    volumes:
      - ./:/var/www
    networks:
      - rimboking
    depends_on:
      - mysql
      - redis

networks:
  rimboking:
    driver: bridge

volumes:
  mysql_data:
